# Brainrex API Explorer
#
# Welcome to the Brainrex API explorer, we make analytics tools for crypto and blockchain. Our currently propiertary models offer sentiment analysis, market making, blockchain monitoring and face-id verification. This AI models can be consumed from this API. We also offer integrations to open data and propietary data providers, as well as free test data we collect. There is a collection of data transformation tools. Join our Telegram group to get the latest news and ask questions [https://t.me/brainrex, #brainrex](https://t.me/brainrex). More about Brainrex at [https://brainrex.com](http://brainrex.com). Full Documentation can be found at [https://brainrexapi.github.io/docs](https://brainrexapi.github.io/docs)
#
# OpenAPI spec version: 0.1.1
# Contact: support@brainrex.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' InlineResponse2002 Class
#'
#' @field blockchain 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2002 <- R6::R6Class(
  'InlineResponse2002',
  public = list(
    `blockchain` = NULL,
    initialize = function(`blockchain`){
      if (!missing(`blockchain`)) {
        stopifnot(is.character(`blockchain`), length(`blockchain`) == 1)
        self$`blockchain` <- `blockchain`
      }
    },
    toJSON = function() {
      InlineResponse2002Object <- list()
      if (!is.null(self$`blockchain`)) {
        InlineResponse2002Object[['blockchain']] <- self$`blockchain`
      }

      InlineResponse2002Object
    },
    fromJSON = function(InlineResponse2002Json) {
      InlineResponse2002Object <- jsonlite::fromJSON(InlineResponse2002Json)
      if (!is.null(InlineResponse2002Object$`blockchain`)) {
        self$`blockchain` <- InlineResponse2002Object$`blockchain`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "blockchain": %s
        }',
        self$`blockchain`
      )
    },
    fromJSONString = function(InlineResponse2002Json) {
      InlineResponse2002Object <- jsonlite::fromJSON(InlineResponse2002Json)
      self$`blockchain` <- InlineResponse2002Object$`blockchain`
    }
  )
)
