# Brainrex API Explorer
#
# Welcome to the Brainrex API explorer, we make analytics tools for crypto and blockchain. Our currently propiertary models offer sentiment analysis, market making, blockchain monitoring and face-id verification. This AI models can be consumed from this API. We also offer integrations to open data and propietary data providers, as well as free test data we collect. There is a collection of data transformation tools. Join our Telegram group to get the latest news and ask questions [https://t.me/brainrex, #brainrex](https://t.me/brainrex). More about Brainrex at [https://brainrex.com](http://brainrex.com). Full Documentation can be found at [https://brainrexapi.github.io/docs](https://brainrexapi.github.io/docs)
#
# OpenAPI spec version: 0.1.1
# Contact: support@brainrex.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' InlineResponse201 Class
#'
#' @field start_date 
#' @field end_date 
#' @field open 
#' @field close 
#' @field high 
#' @field vol 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse201 <- R6::R6Class(
  'InlineResponse201',
  public = list(
    `start_date` = NULL,
    `end_date` = NULL,
    `open` = NULL,
    `close` = NULL,
    `high` = NULL,
    `vol` = NULL,
    initialize = function(`start_date`, `end_date`, `open`, `close`, `high`, `vol`){
      if (!missing(`start_date`)) {
        stopifnot(is.character(`start_date`), length(`start_date`) == 1)
        self$`start_date` <- `start_date`
      }
      if (!missing(`end_date`)) {
        stopifnot(is.character(`end_date`), length(`end_date`) == 1)
        self$`end_date` <- `end_date`
      }
      if (!missing(`open`)) {
        stopifnot(is.numeric(`open`), length(`open`) == 1)
        self$`open` <- `open`
      }
      if (!missing(`close`)) {
        stopifnot(is.numeric(`close`), length(`close`) == 1)
        self$`close` <- `close`
      }
      if (!missing(`high`)) {
        stopifnot(is.numeric(`high`), length(`high`) == 1)
        self$`high` <- `high`
      }
      if (!missing(`vol`)) {
        stopifnot(is.numeric(`vol`), length(`vol`) == 1)
        self$`vol` <- `vol`
      }
    },
    toJSON = function() {
      InlineResponse201Object <- list()
      if (!is.null(self$`start_date`)) {
        InlineResponse201Object[['start_date']] <- self$`start_date`
      }
      if (!is.null(self$`end_date`)) {
        InlineResponse201Object[['end_date']] <- self$`end_date`
      }
      if (!is.null(self$`open`)) {
        InlineResponse201Object[['open']] <- self$`open`
      }
      if (!is.null(self$`close`)) {
        InlineResponse201Object[['close']] <- self$`close`
      }
      if (!is.null(self$`high`)) {
        InlineResponse201Object[['high']] <- self$`high`
      }
      if (!is.null(self$`vol`)) {
        InlineResponse201Object[['vol']] <- self$`vol`
      }

      InlineResponse201Object
    },
    fromJSON = function(InlineResponse201Json) {
      InlineResponse201Object <- jsonlite::fromJSON(InlineResponse201Json)
      if (!is.null(InlineResponse201Object$`start_date`)) {
        self$`start_date` <- InlineResponse201Object$`start_date`
      }
      if (!is.null(InlineResponse201Object$`end_date`)) {
        self$`end_date` <- InlineResponse201Object$`end_date`
      }
      if (!is.null(InlineResponse201Object$`open`)) {
        self$`open` <- InlineResponse201Object$`open`
      }
      if (!is.null(InlineResponse201Object$`close`)) {
        self$`close` <- InlineResponse201Object$`close`
      }
      if (!is.null(InlineResponse201Object$`high`)) {
        self$`high` <- InlineResponse201Object$`high`
      }
      if (!is.null(InlineResponse201Object$`vol`)) {
        self$`vol` <- InlineResponse201Object$`vol`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "start_date": %s,
           "end_date": %s,
           "open": %d,
           "close": %d,
           "high": %d,
           "vol": %d
        }',
        self$`start_date`,
        self$`end_date`,
        self$`open`,
        self$`close`,
        self$`high`,
        self$`vol`
      )
    },
    fromJSONString = function(InlineResponse201Json) {
      InlineResponse201Object <- jsonlite::fromJSON(InlineResponse201Json)
      self$`start_date` <- InlineResponse201Object$`start_date`
      self$`end_date` <- InlineResponse201Object$`end_date`
      self$`open` <- InlineResponse201Object$`open`
      self$`close` <- InlineResponse201Object$`close`
      self$`high` <- InlineResponse201Object$`high`
      self$`vol` <- InlineResponse201Object$`vol`
    }
  )
)
