# Brainrex API Explorer
#
# Welcome to the Brainrex API explorer, we make analytics tools for crypto and blockchain. Our currently propiertary models offer sentiment analysis, market making, blockchain monitoring and face-id verification. This AI models can be consumed from this API. We also offer integrations to open data and propietary data providers, as well as free test data we collect. There is a collection of data transformation tools. Join our Telegram group to get the latest news and ask questions [https://t.me/brainrex, #brainrex](https://t.me/brainrex). More about Brainrex at [https://brainrex.com](http://brainrex.com). Full Documentation can be found at [https://brainrexapi.github.io/docs](https://brainrexapi.github.io/docs)
#
# OpenAPI spec version: 0.1.1
# Contact: support@brainrex.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Request Class
#'
#' @field blockchain 
#' @field market 
#' @field data_format 
#' @field orient 
#' @field start_date 
#' @field end_date 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Request <- R6::R6Class(
  'Request',
  public = list(
    `blockchain` = NULL,
    `market` = NULL,
    `data_format` = NULL,
    `orient` = NULL,
    `start_date` = NULL,
    `end_date` = NULL,
    initialize = function(`blockchain`, `market`, `data_format`, `orient`, `start_date`, `end_date`){
      if (!missing(`blockchain`)) {
        stopifnot(is.character(`blockchain`), length(`blockchain`) == 1)
        self$`blockchain` <- `blockchain`
      }
      if (!missing(`market`)) {
        stopifnot(is.character(`market`), length(`market`) == 1)
        self$`market` <- `market`
      }
      if (!missing(`data_format`)) {
        stopifnot(is.character(`data_format`), length(`data_format`) == 1)
        self$`data_format` <- `data_format`
      }
      if (!missing(`orient`)) {
        stopifnot(is.character(`orient`), length(`orient`) == 1)
        self$`orient` <- `orient`
      }
      if (!missing(`start_date`)) {
        stopifnot(is.character(`start_date`), length(`start_date`) == 1)
        self$`start_date` <- `start_date`
      }
      if (!missing(`end_date`)) {
        stopifnot(is.character(`end_date`), length(`end_date`) == 1)
        self$`end_date` <- `end_date`
      }
    },
    toJSON = function() {
      RequestObject <- list()
      if (!is.null(self$`blockchain`)) {
        RequestObject[['blockchain']] <- self$`blockchain`
      }
      if (!is.null(self$`market`)) {
        RequestObject[['market']] <- self$`market`
      }
      if (!is.null(self$`data_format`)) {
        RequestObject[['data_format']] <- self$`data_format`
      }
      if (!is.null(self$`orient`)) {
        RequestObject[['orient']] <- self$`orient`
      }
      if (!is.null(self$`start_date`)) {
        RequestObject[['start_date']] <- self$`start_date`
      }
      if (!is.null(self$`end_date`)) {
        RequestObject[['end_date']] <- self$`end_date`
      }

      RequestObject
    },
    fromJSON = function(RequestJson) {
      RequestObject <- jsonlite::fromJSON(RequestJson)
      if (!is.null(RequestObject$`blockchain`)) {
        self$`blockchain` <- RequestObject$`blockchain`
      }
      if (!is.null(RequestObject$`market`)) {
        self$`market` <- RequestObject$`market`
      }
      if (!is.null(RequestObject$`data_format`)) {
        self$`data_format` <- RequestObject$`data_format`
      }
      if (!is.null(RequestObject$`orient`)) {
        self$`orient` <- RequestObject$`orient`
      }
      if (!is.null(RequestObject$`start_date`)) {
        self$`start_date` <- RequestObject$`start_date`
      }
      if (!is.null(RequestObject$`end_date`)) {
        self$`end_date` <- RequestObject$`end_date`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "blockchain": %s,
           "market": %s,
           "data_format": %s,
           "orient": %s,
           "start_date": %s,
           "end_date": %s
        }',
        self$`blockchain`,
        self$`market`,
        self$`data_format`,
        self$`orient`,
        self$`start_date`,
        self$`end_date`
      )
    },
    fromJSONString = function(RequestJson) {
      RequestObject <- jsonlite::fromJSON(RequestJson)
      self$`blockchain` <- RequestObject$`blockchain`
      self$`market` <- RequestObject$`market`
      self$`data_format` <- RequestObject$`data_format`
      self$`orient` <- RequestObject$`orient`
      self$`start_date` <- RequestObject$`start_date`
      self$`end_date` <- RequestObject$`end_date`
    }
  )
)
