# Brainrex API Explorer
#
# Welcome to the Brainrex API explorer, we make analytics tools for crypto and blockchain. Our currently propiertary models offer sentiment analysis, market making, blockchain monitoring and face-id verification. This AI models can be consumed from this API. We also offer integrations to open data and propietary data providers, as well as free test data we collect. There is a collection of data transformation tools. Join our Telegram group to get the latest news and ask questions [https://t.me/brainrex, #brainrex](https://t.me/brainrex). More about Brainrex at [https://brainrex.com](http://brainrex.com). Full Documentation can be found at [https://brainrexapi.github.io/docs](https://brainrexapi.github.io/docs)
#
# OpenAPI spec version: 0.1.1
# Contact: support@brainrex.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Text1 Class
#'
#' @field text 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Text1 <- R6::R6Class(
  'Text1',
  public = list(
    `text` = NULL,
    initialize = function(`text`){
      if (!missing(`text`)) {
        stopifnot(is.character(`text`), length(`text`) == 1)
        self$`text` <- `text`
      }
    },
    toJSON = function() {
      Text1Object <- list()
      if (!is.null(self$`text`)) {
        Text1Object[['text']] <- self$`text`
      }

      Text1Object
    },
    fromJSON = function(Text1Json) {
      Text1Object <- jsonlite::fromJSON(Text1Json)
      if (!is.null(Text1Object$`text`)) {
        self$`text` <- Text1Object$`text`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "text": %s
        }',
        self$`text`
      )
    },
    fromJSONString = function(Text1Json) {
      Text1Object <- jsonlite::fromJSON(Text1Json)
      self$`text` <- Text1Object$`text`
    }
  )
)
